Processing data in models
dieum512/Blogg-app-2 pull request #2
Opened 2023-08-16 20:34 UTC by dieum512

In this milestone I:

- [x] Set up associations between models.
- [x] Wrote SQL queries with Active Record.
- [x] Created model classes for all entities as shown in the ERD diagram
- [x] Set up associations between models.
- [x] Used models to insert data
- [x] Createed custom methods

Thanks for taking the time to correct this work :ok_hand:

2023-08-16 21:35 UTC, Felix45 requested changes
Hi @dieum512, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Most models are setup correctly :white_check_mark: 
- [x] All migrations run without errors :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:    

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-16 21:35 UTC, Felix45 commented on app/models/comment.rb
> +class Like < ApplicationRecord
- [ Required ] I think it would be better if the name of this model is `Comment` since this is supposed to be the comments model. Currently, I get the error below when I try to create a comment. Please see the screenshot below and rectify this.

## Error screenshot
![Screenshot from 2023-08-17 00-03-22](https://github.com/dieum512/Blogg-app-2/assets/16392046/13ba2986-3511-40a7-b2a5-2df68ae72472)

2023-08-16 21:35 UTC, Felix45 commented on app/models/comment.rb
> +  end
- [ Required ] I think it would be best if these two methods refer to the `comments_counter` in the `posts` table according to your schema, currently, the methods refer to a non-existent column called `comments_count`. This typo causes the error below which prevents the update of the `comments_counter` column in the `posts` table. Please see the screenshot below and rectify this.

## Error screenshot
![Screenshot from 2023-08-16 23-59-49](https://github.com/dieum512/Blogg-app-2/assets/16392046/e5477022-7727-4c7a-b406-216e8b62c6ca)

2023-08-16 21:35 UTC, Felix45 commented on app/models/like.rb
> +end
- [ Required ] I think it would be better if you fix this class so that it's able to create a `Like` and update the `likes_counter` column in the `posts` table when a new like is created. Currently, this class is not updating the `likes_counter` column in the `posts` table because it is not spelled correctly in this file. I would like to suggest that you refactor the code in this class as shown below so as to fix this error.

## Example code
> > I would like to suggest that you use a *[Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - *`after_save` to call the `#update_post_likes_counter` method every time a new like has been saved to database, then make the `update_post_likes_counter` method private. This will ensure that the `likes_counter` in the `posts` table is updated anytime a new like has been created.

```ruby
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_post_likes_counter

  private
  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end
```
## Error screenshot
![Screenshot from 2023-08-16 23-55-30](https://github.com/dieum512/Blogg-app-2/assets/16392046/c9e665a1-8afd-4c4e-9c9c-70fb3da5ab8b)

2023-08-16 21:35 UTC, Felix45 commented on app/models/user.rb
- [ Optional ] This review is related to the readme file, I think it would be better if you add a `LICENSE` file to the root of your project directory and then update the License link on the readme file to prevent the `404` page not found error that I've just experienced. A functioning license link informs someone who would like to use your project how to use it within the boundaries of the law. It's therefore very important to have it, kindly rectify this.

## Error screenshot
![Screenshot from 2023-08-17 00-27-36](https://github.com/dieum512/Blogg-app-2/assets/16392046/0355523c-ff5c-411a-b66b-86f6ba7dd094)

- [ Required ] This review is related to the readme file, in the readme file I've noticed that the _Getting Started_ section is not descriptive enough, it doesn't give meaningful steps on how to set up this project. I would like to suggest that you update this section as shown below.

## Getting Started

To get a local copy up and running follow these simple example steps.

### Prerequisites
```
  Ruby
  Ruby on Rails
  PostgreSQL
```
### Setup
Clone the repository and change the directory to blog

``` 
  $ git clone git@github.com:dieum512/Blogg-app-2.git

  $ cd Blogg-app-2
```

### Install
Install all project dependencies by running the command below
 
``` 
  $ bundle install
```

### Run the application
```
  $ bin/rails server
```

### Visit the homepage of application
```
  $ http://localhost:3000/
```
## Run tests
To run tests, run the following command:

Example command:
```
 $ rspec spec_name
```

2023-08-17 05:09 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @dieum512 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 05:09 UTC, tresorsawasawa commented on app/models/user.rb
> +end
`README` file:

- [ ] As  mentioned by the previous reviewer and to make your documentation be more professional and descriptive, kindly ensure that your update your `Getting started` section with correct an appropriate info content to each sub-section such as how `clone` your repo, `access` the cloned directory, `install` bundles, `create db`, `run` your app,.. To help you, I suggest you refer this **[gist_file](https://gist.github.com/tresorsawasawa/4cde69cff1b40161b9de380f9891f415)**

2023-08-18 16:55 UTC, merged